import { Icon } from './icon.interface';

export const Icons: Icon[] = [
  { name: 'search', identifier: 'search' },
  { name: 'home', identifier: 'home' },
  { name: 'account circle', identifier: 'account_circle' },
  { name: 'settings', identifier: 'settings' },
  { name: 'done', identifier: 'done' },
  { name: 'info', identifier: 'info' },
  { name: 'check circle', identifier: 'check_circle' },
  { name: 'delete', identifier: 'delete' },
  { name: 'shopping cart', identifier: 'shopping_cart' },
  { name: 'visibility', identifier: 'visibility' },
  { name: 'favorite', identifier: 'favorite' },
  { name: 'logout', identifier: 'logout' },
  { name: 'description', identifier: 'description' },
  { name: 'favorite border', identifier: 'favorite_border' },
  { name: 'lock', identifier: 'lock' },
  { name: 'schedule', identifier: 'schedule' },
  { name: 'language', identifier: 'language' },
  { name: 'face', identifier: 'face' },
  { name: 'help outline', identifier: 'help_outline' },
  { name: 'manage accounts', identifier: 'manage_accounts' },
  { name: 'filter alt', identifier: 'filter_alt' },
  { name: 'fingerprint', identifier: 'fingerprint' },
  { name: 'event', identifier: 'event' },
  { name: 'verified', identifier: 'verified' },
  { name: 'thumb up', identifier: 'thumb_up' },
  { name: 'dashboard', identifier: 'dashboard' },
  { name: 'login', identifier: 'login' },
  { name: 'calendar today', identifier: 'calendar_today' },
  { name: 'visibility off', identifier: 'visibility_off' },
  { name: 'list', identifier: 'list' },
  { name: 'check circle outline', identifier: 'check_circle_outline' },
  { name: 'highlight off', identifier: 'highlight_off' },
  { name: 'date range', identifier: 'date_range' },
  { name: 'help', identifier: 'help' },
  { name: 'question answer', identifier: 'question_answer' },
  { name: 'task alt', identifier: 'task_alt' },
  { name: 'paid', identifier: 'paid' },
  { name: 'article', identifier: 'article' },
  { name: 'shopping bag', identifier: 'shopping_bag' },
  { name: 'lightbulb', identifier: 'lightbulb' },
  { name: 'open in new', identifier: 'open_in_new' },
  { name: 'perm identity', identifier: 'perm_identity' },
  { name: 'trending up', identifier: 'trending_up' },
  { name: 'credit card', identifier: 'credit_card' },
  { name: 'history', identifier: 'history' },
  { name: 'account balance', identifier: 'account_balance' },
  { name: 'delete outline', identifier: 'delete_outline' },
  { name: 'report problem', identifier: 'report_problem' },
  { name: 'fact check', identifier: 'fact_check' },
  { name: 'assignment', identifier: 'assignment' },
  { name: 'verified user', identifier: 'verified_user' },
  { name: 'arrow right alt', identifier: 'arrow_right_alt' },
  { name: 'star rate', identifier: 'star_rate' },
  { name: 'account balance wallet', identifier: 'account_balance_wallet' },
  { name: 'analytics', identifier: 'analytics' },
  { name: 'autorenew', identifier: 'autorenew' },
  { name: 'work', identifier: 'work' },
  { name: 'build', identifier: 'build' },
  { name: 'view list', identifier: 'view_list' },
  { name: 'print', identifier: 'print' },
  { name: 'store', identifier: 'store' },
  { name: 'today', identifier: 'today' },
  { name: 'delete forever', identifier: 'delete_forever' },
  { name: 'admin panel settings', identifier: 'admin_panel_settings' },
  { name: 'lock open', identifier: 'lock_open' },
  { name: 'savings', identifier: 'savings' },
  { name: 'room', identifier: 'room' },
  { name: 'code', identifier: 'code' },
  { name: 'grade', identifier: 'grade' },
  { name: 'watch later', identifier: 'watch_later' },
  { name: 'receipt', identifier: 'receipt' },
  { name: 'update', identifier: 'update' },
  { name: 'add shopping cart', identifier: 'add_shopping_cart' },
  { name: 'contact support', identifier: 'contact_support' },
  { name: 'power settings new', identifier: 'power_settings_new' },
  { name: 'pets', identifier: 'pets' },
  { name: 'done all', identifier: 'done_all' },
  { name: 'explore', identifier: 'explore' },
  { name: 'bookmark', identifier: 'bookmark' },
  { name: 'bookmark border', identifier: 'bookmark_border' },
  { name: 'note add', identifier: 'note_add' },
  { name: 'reorder', identifier: 'reorder' },
  { name: 'account box', identifier: 'account_box' },
  { name: 'shopping basket', identifier: 'shopping_basket' },
  { name: 'pending actions', identifier: 'pending_actions' },
  { name: 'drag indicator', identifier: 'drag_indicator' },
  { name: 'payment', identifier: 'payment' },
  { name: 'launch', identifier: 'launch' },
  { name: 'supervisor account', identifier: 'supervisor_account' },
  { name: 'pending', identifier: 'pending' },
  { name: 'zoom in', identifier: 'zoom_in' },
  { name: 'touch app', identifier: 'touch_app' },
  { name: 'assessment', identifier: 'assessment' },
  { name: 'calendar month', identifier: 'calendar_month' },
  { name: 'thumb up off alt', identifier: 'thumb_up_off_alt' },
  { name: 'open in full', identifier: 'open_in_full' },
  { name: 'leaderboard', identifier: 'leaderboard' },
  { name: 'done outline', identifier: 'done_outline' },
  { name: 'exit to app', identifier: 'exit_to_app' },
  { name: 'preview', identifier: 'preview' },
  { name: 'assignment_ind', identifier: 'assignment_ind' },
  { name: 'card giftcard', identifier: 'card_giftcard' },
  { name: 'view in ar', identifier: 'view_in_ar' },
  { name: 'work outline', identifier: 'work_outline' },
  { name: 'feedback', identifier: 'feedback' },
  { name: 'published with changes', identifier: 'published_with_changes' },
  { name: 'timeline', identifier: 'timeline' },
  { name: 'dns', identifier: 'dns' },
  { name: 'swap horiz', identifier: 'swap_horiz' },
  { name: 'assignment turned in', identifier: 'assignment_turned_in' },
  { name: 'sync alt', identifier: 'sync_alt' },
  { name: 'flight takeoff', identifier: 'flight_takeoff' },
  { name: 'book', identifier: 'book' },
  { name: 'stars', identifier: 'stars' },
  { name: 'label', identifier: 'label' },
  { name: 'pan tool', identifier: 'pan_tool' },
  { name: 'bug report', identifier: 'bug_report' },
  { name: 'contact page', identifier: 'contact_page' },
  { name: 'gavel', identifier: 'gavel' },
  { name: 'cached', identifier: 'cached' },
  { name: 'translate', identifier: 'translate' },
  { name: 'alarm', identifier: 'alarm' },
  { name: 'space dashboard', identifier: 'space_dashboard' },
  { name: 'android', identifier: 'android' },
  { name: 'supervised user circle', identifier: 'supervised_user_circle' },
  { name: 'accessibility', identifier: 'accessibility' },
  { name: 'edit calendar', identifier: 'edit_calendar' },
  { name: 'minimize', identifier: 'minimize' },
  { name: 'extension', identifier: 'extension' },
  { name: 'get app', identifier: 'get_app' },
  { name: 'tips and updates', identifier: 'tips_and_updates' },
  { name: 'record voice over', identifier: 'record_voice_over' },
  { name: 'add task', identifier: 'add_task' },
  { name: 'trending flat', identifier: 'trending_flat' },
  { name: 'hourglass empty', identifier: 'hourglass_empty' },
  { name: 'help center', identifier: 'help_center' },
  { name: 'thumb down', identifier: 'thumb_down' },
  { name: 'accessibility new', identifier: 'accessibility_new' },
  { name: 'sticky note 2', identifier: 'sticky_note_2' },
  { name: 'flutter dash', identifier: 'flutter_dash' },
  { name: 'rule', identifier: 'rule' },
  { name: 'dashboard customize', identifier: 'dashboard_customize' },
  { name: 'support', identifier: 'support' },
  { name: 'source', identifier: 'source' },
  { name: 'find in page', identifier: 'find_in_page' },
  { name: 'close fullscreen', identifier: 'close_fullscreen' },
  { name: 'settings applications', identifier: 'settings_applications' },
  { name: 'view headline', identifier: 'view_headline' },
  { name: 'redeem', identifier: 'redeem' },
  { name: 'announcement', identifier: 'announcement' },
  { name: 'loyalty', identifier: 'loyalty' },
  { name: 'group work', identifier: 'group_work' },
  { name: 'ads click', identifier: 'ads_click' },
  { name: 'swap vert', identifier: 'swap_vert' },
  { name: 'restore', identifier: 'restore' },
  { name: 'euro symbol', identifier: 'euro_symbol' },
  { name: 'sensors', identifier: 'sensors' },
  { name: 'dangerous', identifier: 'dangerous' },
  { name: 'compare arrows', identifier: 'compare_arrows' },
  { name: 'nightlight round', identifier: 'nightlight_round' },
  { name: 'privacy tip', identifier: 'privacy_tip' },
  { name: 'subject', identifier: 'subject' },
  { name: 'rocket launch', identifier: 'rocket_launch' },
  { name: 'arrow circle right', identifier: 'arrow_circle_right' },
  { name: 'question mark', identifier: 'question_mark' },
  { name: 'disabled by default', identifier: 'disabled_by_default' },
  { name: 'track changes', identifier: 'track_changes' },
  { name: 'grading', identifier: 'grading' },
  { name: 'https', identifier: 'https' },
  { name: 'table view', identifier: 'table_view' },
  { name: 'copyright', identifier: 'copyright' },
  { name: 'toc', identifier: 'toc' },
  { name: 'arrow circle up', identifier: 'arrow_circle_up' },
  { name: 'bookmarks', identifier: 'bookmarks' },
  { name: 'api', identifier: 'api' },
  { name: 'query builder', identifier: 'query_builder' },
  { name: 'perm media', identifier: 'perm_media' },
  { name: 'build circle', identifier: 'build_circle' },
  { name: 'input', identifier: 'input' },
  { name: 'book online', identifier: 'book_online' },
  { name: 'zoom out', identifier: 'zoom_out' },
  { name: 'backup', identifier: 'backup' },
  { name: 'perm contact calendar', identifier: 'perm_contact_calendar' },
  { name: 'open with', identifier: 'open_with' },
  { name: 'view module', identifier: 'view_module' },
  { name: 'settings phone', identifier: 'settings_phone' },
  { name: 'circle notifications', identifier: 'circle_notifications' },
  { name: '3d rotation', identifier: '3d_rotation' },
  { name: 'speaker notes', identifier: 'speaker_notes' },
  { name: 'arrow circle down', identifier: 'arrow_circle_down' },
  { name: 'label important', identifier: 'label_important' },
  { name: 'card membership', identifier: 'card_membership' },
  { name: 'perm phone msg', identifier: 'perm_phone_msg' },
  { name: 'file present', identifier: 'file_present' },
  { name: 'wysiwyg', identifier: 'wysiwyg' },
  { name: 'swipe', identifier: 'swipe' },
  { name: 'pageview', identifier: 'pageview' },
  {
    name: 'integration instructions',
    identifier: 'integration_instructions',
  },
  { name: 'upgrade', identifier: 'upgrade' },
  { name: 'trending down', identifier: 'trending_down' },
  { name: 'change history', identifier: 'change_history' },
  { name: 'class', identifier: 'class' },
  { name: 'accessible', identifier: 'accessible' },
  { name: 'g translate', identifier: 'g_translate' },
  { name: 'settings accessibility', identifier: 'settings_accessibility' },
  {
    name: 'production quantity limits',
    identifier: 'production_quantity_limits',
  },
  { name: 'offline bolt', identifier: 'offline_bolt' },
  { name: 'expand', identifier: 'expand' },
  { name: 'model training', identifier: 'model_training' },
  { name: 'aspect ratio', identifier: 'aspect_ratio' },
  { name: 'donut large', identifier: 'donut_large' },
  { name: 'calendar view month', identifier: 'calendar_view_month' },
  { name: 'settings backup restore', identifier: 'settings_backup_restore' },
  { name: 'segment', identifier: 'segment' },
  { name: 'maximize', identifier: 'maximize' },
  { name: 'schedule send', identifier: 'schedule_send' },
  { name: 'view column', identifier: 'view_column' },
  { name: 'bookmark add', identifier: 'bookmark_add' },
  { name: 'arrow circle left', identifier: 'arrow_circle_left' },
  { name: 'alarm on', identifier: 'alarm_on' },
  { name: 'thumbs up down', identifier: 'thumbs_up_down' },
  { name: 'thumb down off alt', identifier: 'thumb_down_off_alt' },
  { name: 'percent', identifier: 'percent' },
  { name: 'view agenda', identifier: 'view_agenda' },
  { name: 'settings ethernet', identifier: 'settings_ethernet' },
  { name: 'theaters', identifier: 'theaters' },
  { name: 'important devices', identifier: 'important_devices' },
  { name: 'invert colors', identifier: 'invert_colors' },
  { name: 'unpublished', identifier: 'unpublished' },
  { name: 'open in browser', identifier: 'open_in_browser' },
  { name: 'currency exchange', identifier: 'currency_exchange' },
  { name: 'commute', identifier: 'commute' },
  { name: 'opacity', identifier: 'opacity' },
  { name: 'addchart', identifier: 'addchart' },
  { name: 'no accounts', identifier: 'no_accounts' },
  { name: 'youtube searched for', identifier: 'youtube_searched_for' },
  { name: 'history toggle off', identifier: 'history_toggle_off' },
  { name: 'view week', identifier: 'view_week' },
  { name: 'tour', identifier: 'tour' },
  { name: 'system update alt', identifier: 'system_update_alt' },
  { name: 'settings input antenna', identifier: 'settings_input_antenna' },
  { name: 'shop', identifier: 'shop' },
  { name: 'turned in', identifier: 'turned_in' },
  { name: 'mark as unread', identifier: 'mark_as_unread' },
  { name: 'bookmark added', identifier: 'bookmark_added' },
  { name: 'hide source', identifier: 'hide_source' },
  { name: 'plagiarism', identifier: 'plagiarism' },
  { name: 'flight land', identifier: 'flight_land' },
  { name: 'search off', identifier: 'search_off' },
  { name: 'not started', identifier: 'not_started' },
  { name: 'saved search', identifier: 'saved_search' },
  { name: 'contactless', identifier: 'contactless' },
  { name: 'assignment late', identifier: 'assignment_late' },
  { name: 'donut small', identifier: 'donut_small' },
  { name: 'highlight alt', identifier: 'highlight_alt' },
  { name: 'view carousel', identifier: 'view_carousel' },
  { name: 'anchor', identifier: 'anchor' },
  {
    name: 'settings input component',
    identifier: 'settings_input_component',
  },
  { name: 'turned in not', identifier: 'turned_in_not' },
  { name: 'mediation', identifier: 'mediation' },
  { name: 'fit screen', identifier: 'fit_screen' },
  { name: 'toll', identifier: 'toll' },
  { name: 'edit off', identifier: 'edit_off' },
  { name: 'flaky', identifier: 'flaky' },
  { name: 'settings remote', identifier: 'settings_remote' },
  { name: 'assignment return', identifier: 'assignment_return' },
  { name: 'view quilt', identifier: 'view_quilt' },
  { name: 'remove shopping cart', identifier: 'remove_shopping_cart' },
  { name: 'all inbox', identifier: 'all_inbox' },
  { name: 'hourglass full', identifier: 'hourglass_full' },
  { name: 'lock clock', identifier: 'lock_clock' },
  { name: 'settings voice', identifier: 'settings_voice' },
  { name: 'online prediction', identifier: 'online_prediction' },
  { name: 'pregnant woman', identifier: 'pregnant_woman' },
  { name: 'swap horizontal circle', identifier: 'swap_horizontal_circle' },
  { name: 'hotel class', identifier: 'hotel_class' },
  { name: 'event seat', identifier: 'event_seat' },
  { name: 'next plan', identifier: 'next_plan' },
  { name: 'view sidebar', identifier: 'view_sidebar' },
  { name: 'camera enhance', identifier: 'camera_enhance' },
  { name: 'markunread mailbox', identifier: 'markunread_mailbox' },
  { name: 'restore from trash', identifier: 'restore_from_trash' },
  { name: 'vertical split', identifier: 'vertical_split' },
  { name: 'dynamic form', identifier: 'dynamic_form' },
  { name: 'calendar view week', identifier: 'calendar_view_week' },
  { name: 'accessible forward', identifier: 'accessible_forward' },
  { name: 'tab', identifier: 'tab' },
  { name: 'balance', identifier: 'balance' },
  { name: 'filter alt off', identifier: 'filter_alt_off' },
  { name: 'add to drive', identifier: 'add_to_drive' },
  { name: 'data exploration', identifier: 'data_exploration' },
  { name: 'shopping cart checkout', identifier: 'shopping_cart_checkout' },
  { name: 'settings power', identifier: 'settings_power' },
  { name: 'view stream', identifier: 'view_stream' },
  { name: 'remove done', identifier: 'remove_done' },
  { name: 'smart button', identifier: 'smart_button' },
  { name: 'request page', identifier: 'request_page' },
  { name: 'card travel', identifier: 'card_travel' },
  { name: 'try', identifier: 'try' },
  { name: 'outbox', identifier: 'outbox' },
  { name: 'offline pin', identifier: 'offline_pin' },
  { name: 'rowing', identifier: 'rowing' },
  { name: 'calendar view day', identifier: 'calendar_view_day' },
  { name: 'outlet', identifier: 'outlet' },
  { name: 'find replace', identifier: 'find_replace' },
  { name: 'compress', identifier: 'compress' },
  { name: 'rocket', identifier: 'rocket' },
  { name: 'chrome reader mode', identifier: 'chrome_reader_mode' },
  { name: 'token', identifier: 'token' },
  { name: 'settings brightness', identifier: 'settings_brightness' },
  { name: 'http', identifier: 'http' },
  { name: 'alarm add', identifier: 'alarm_add' },
  { name: 'assignment returned', identifier: 'assignment_returned' },
  { name: 'spellcheck', identifier: 'spellcheck' },
  { name: 'play for work', identifier: 'play_for_work' },
  { name: 'gif', identifier: 'gif' },
  { name: 'backup table', identifier: 'backup_table' },
  { name: 'restore page', identifier: 'restore_page' },
  { name: 'credit card off', identifier: 'credit_card_off' },
  { name: 'wifi protected setup', identifier: 'wifi_protected_setup' },
  { name: 'settings overscan', identifier: 'settings_overscan' },
  { name: 'new label', identifier: 'new_label' },
  { name: 'lock reset', identifier: 'lock_reset' },
  { name: 'fax', identifier: 'fax' },
  {
    name: 'settings input composite',
    identifier: 'settings_input_composite',
  },
  { name: 'generating tokens', identifier: 'generating_tokens' },
  { name: 'quickreply', identifier: 'quickreply' },
  { name: 'comment bank', identifier: 'comment_bank' },
  { name: 'view day', identifier: 'view_day' },
  { name: 'terminal', identifier: 'terminal' },
  { name: 'swap vertical circle', identifier: 'swap_vertical_circle' },
  { name: 'polymer', identifier: 'polymer' },
  { name: 'outbound', identifier: 'outbound' },
  { name: 'line weight', identifier: 'line_weight' },
  { name: 'cancel schedule send', identifier: 'cancel_schedule_send' },
  { name: 'horizontal split', identifier: 'horizontal_split' },
  { name: 'batch prediction', identifier: 'batch_prediction' },
  { name: 'send and archive', identifier: 'send_and_archive' },
  { name: 'picture in picture', identifier: 'picture_in_picture' },
  { name: 'free cancellation', identifier: 'free_cancellation' },
  { name: 'density medium', identifier: 'density_medium' },
  { name: 'code off', identifier: 'code_off' },
  { name: 'settings bluetooth', identifier: 'settings_bluetooth' },
  { name: 'bookmark remove', identifier: 'bookmark_remove' },
  { name: 'disabled visible', identifier: 'disabled_visible' },
  { name: 'switch access shortcut', identifier: 'switch_access_shortcut' },
  { name: 'flip to front', identifier: 'flip_to_front' },
  { name: 'shop two', identifier: 'shop_two' },
  { name: 'gif box', identifier: 'gif_box' },
  { name: 'add card', identifier: 'add_card' },
  { name: 'eject', identifier: 'eject' },
  { name: 'speaker notes off', identifier: 'speaker_notes_off' },
  { name: 'satellite alt', identifier: 'satellite_alt' },
  { name: 'perm data setting', identifier: 'perm_data_setting' },
  { name: 'view timeline', identifier: 'view_timeline' },
  { name: 'settings input hdmi', identifier: 'settings_input_hdmi' },
  { name: 'perm scan wifi', identifier: 'perm_scan_wifi' },
  { name: 'alarm off', identifier: 'alarm_off' },
  { name: 'settings cell', identifier: 'settings_cell' },
  { name: 'hourglass disabled', identifier: 'hourglass_disabled' },
  { name: 'app blocking', identifier: 'app_blocking' },
  { name: 'sensors off', identifier: 'sensors_off' },
  { name: 'work off', identifier: 'work_off' },
  { name: 'line style', identifier: 'line_style' },
  { name: 'webhook', identifier: 'webhook' },
  { name: 'perm device information', identifier: 'perm_device_information' },
  { name: 'picture in picture alt', identifier: 'picture_in_picture_alt' },
  { name: 'subtitles off', identifier: 'subtitles_off' },
  { name: 'assured workload', identifier: 'assured_workload' },
  { name: 'html', identifier: 'html' },
  { name: '123', identifier: '123' },
  {
    name: 'switch access shortcut add',
    identifier: 'switch_access_shortcut_add',
  },
  { name: 'display settings', identifier: 'display_settings' },
  { name: 'update disabled', identifier: 'update_disabled' },
  { name: 'event repeat', identifier: 'event_repeat' },
  { name: 'settings input svideo', identifier: 'settings_input_svideo' },
  { name: 'voice over off', identifier: 'voice_over_off' },
  { name: 'output', identifier: 'output' },
  { name: 'view array', identifier: 'view_array' },
  { name: 'flip to back', identifier: 'flip_to_back' },
  { name: 'open in new off', identifier: 'open_in_new_off' },
  { name: 'swipe left', identifier: 'swipe_left' },
  { name: 'noise control off', identifier: 'noise_control_off' },
  { name: 'all out', identifier: 'all_out' },
  { name: 'javascript', identifier: 'javascript' },
  { name: 'private connectivity', identifier: 'private_connectivity' },
  { name: 'work history', identifier: 'work_history' },
  { name: 'app shortcut', identifier: 'app_shortcut' },
  { name: 'label off', identifier: 'label_off' },
  { name: 'rounded corner', identifier: 'rounded_corner' },
  { name: 'join full', identifier: 'join_full' },
  { name: 'tab unselected', identifier: 'tab_unselected' },
  { name: 'shop 2', identifier: 'shop_2' },
  { name: 'text rotate vertical', identifier: 'text_rotate_vertical' },
  { name: 'swipe right', identifier: 'swipe_right' },
  { name: 'explore off', identifier: 'explore_off' },
  { name: 'pan tool alt', identifier: 'pan_tool_alt' },
  { name: 'install desktop', identifier: 'install_desktop' },
  { name: 'abc', identifier: 'abc' },
  { name: 'text rotation none', identifier: 'text_rotation_none' },
  { name: 'swipe up', identifier: 'swipe_up' },
  { name: 'not accessible', identifier: 'not_accessible' },
  { name: 'pin invoke', identifier: 'pin_invoke' },
  { name: 'join inner', identifier: 'join_inner' },
  { name: 'perm camera mic', identifier: 'perm_camera_mic' },
  { name: 'manage history', identifier: 'manage_history' },
  { name: 'extension off', identifier: 'extension_off' },
  { name: 'density small', identifier: 'density_small' },
  { name: 'data thresholding', identifier: 'data_thresholding' },
  { name: 'lightbulb circle', identifier: 'lightbulb_circle' },
  { name: 'pin end', identifier: 'pin_end' },
  { name: 'install mobile', identifier: 'install_mobile' },
  { name: 'commit', identifier: 'commit' },
  { name: 'swipe down', identifier: 'swipe_down' },
  { name: 'text rotate up', identifier: 'text_rotate_up' },
  { name: 'css', identifier: 'css' },
  { name: 'text rotation down', identifier: 'text_rotation_down' },
  { name: 'join left', identifier: 'join_left' },
  { name: 'text rotation angledown', identifier: 'text_rotation_angledown' },
  { name: 'view kanban', identifier: 'view_kanban' },
  { name: 'text rotation angleup', identifier: 'text_rotation_angleup' },
  { name: 'pinch', identifier: 'pinch' },
  { name: 'swipe vertical', identifier: 'swipe_vertical' },
  { name: 'view cozy', identifier: 'view_cozy' },
  { name: 'join right', identifier: 'join_right' },
  { name: 'swipe right alt', identifier: 'swipe_right_alt' },
  { name: 'view comfy alt', identifier: 'view_comfy_alt' },
  { name: 'spatial audio off', identifier: 'spatial_audio_off' },
  { name: 'noise aware', identifier: 'noise_aware' },
  { name: 'php', identifier: 'php' },
  { name: 'view compact alt', identifier: 'view_compact_alt' },
  { name: 'swipe down alt', identifier: 'swipe_down_alt' },
  { name: 'browse gallery', identifier: 'browse_gallery' },
  { name: 'swipe left alt', identifier: 'swipe_left_alt' },
  { name: 'network ping', identifier: 'network_ping' },
  { name: 'swipe up alt', identifier: 'swipe_up_alt' },
  { name: 'density large', identifier: 'density_large' },
  { name: 'lock person', identifier: 'lock_person' },
  { name: 'on device training', identifier: 'on_device_training' },
  { name: 'spatial tracking', identifier: 'spatial_tracking' },
  { name: 'spatial audio', identifier: 'spatial_audio' },
  { name: 'hls', identifier: 'hls' },
  { name: 'troubleshoot', identifier: 'troubleshoot' },
  { name: 'hls off', identifier: 'hls_off' },
  { name: 'width normal', identifier: 'width_normal' },
  { name: 'width full', identifier: 'width_full' },
  { name: 'width wide', identifier: 'width_wide' },
  { name: 'face unlock', identifier: 'face_unlock' },
  { name: 'arrow outward', identifier: 'arrow_outward' },
  { name: 'add home', identifier: 'add_home' },
  { name: 'unfold more double', identifier: 'unfold_more_double' },
  { name: 'repartition', identifier: 'repartition' },
  { name: 'unfold less double', identifier: 'unfold_less_double' },
  { name: 'transcribe', identifier: 'transcribe' },
  { name: 'warning', identifier: 'warning' },
  { name: 'error', identifier: 'error' },
  { name: 'error outline', identifier: 'error_outline' },
  { name: 'warning amber', identifier: 'warning_amber' },
  { name: 'notification important', identifier: 'notification_important' },
  { name: 'add alert', identifier: 'add_alert' },
  { name: 'auto delete', identifier: 'auto_delete' },
  { name: 'play arrow', identifier: 'play_arrow' },
  { name: 'play circle filled', identifier: 'play_circle_filled' },
  { name: 'videocam', identifier: 'videocam' },
  { name: 'play circle', identifier: 'play_circle' },
  { name: 'mic', identifier: 'mic' },
  { name: 'volume up', identifier: 'volume_up' },
  { name: 'pause', identifier: 'pause' },
  { name: 'library books', identifier: 'library_books' },
  { name: 'speed', identifier: 'speed' },
  { name: 'stop', identifier: 'stop' },
  { name: 'fiber manual record', identifier: 'fiber_manual_record' },
  { name: 'movie', identifier: 'movie' },
  { name: 'skip next', identifier: 'skip_next' },
  { name: 'playlist add', identifier: 'playlist_add' },
  { name: 'new releases', identifier: 'new_releases' },
  { name: 'equalizer', identifier: 'equalizer' },
  { name: 'loop', identifier: 'loop' },
  { name: 'fast forward', identifier: 'fast_forward' },
  { name: 'web', identifier: 'web' },
  { name: 'video library', identifier: 'video_library' },
  { name: 'playlist add check', identifier: 'playlist_add_check' },
  { name: 'mic off', identifier: 'mic_off' },
  { name: 'library add', identifier: 'library_add' },
  { name: 'video call', identifier: 'video_call' },
  { name: 'pause circle', identifier: 'pause_circle' },
  { name: 'subscriptions', identifier: 'subscriptions' },
  { name: 'repeat', identifier: 'repeat' },
  { name: 'stop circle', identifier: 'stop_circle' },
  { name: 'volume mute', identifier: 'volume_mute' },
  { name: 'shuffle', identifier: 'shuffle' },
  { name: 'not interested', identifier: 'not_interested' },
  { name: 'sort by alpha', identifier: 'sort_by_alpha' },
  { name: 'mic none', identifier: 'mic_none' },
  { name: 'library music', identifier: 'library_music' },
  { name: 'fast rewind', identifier: 'fast_rewind' },
  { name: 'videocam off', identifier: 'videocam_off' },
  { name: 'volume down', identifier: 'volume_down' },
  { name: 'queue music', identifier: 'queue_music' },
  { name: 'recent actors', identifier: 'recent_actors' },
  { name: 'web asset', identifier: 'web_asset' },
  { name: 'pause circle filled', identifier: 'pause_circle_filled' },
  { name: 'hearing', identifier: 'hearing' },
  { name: 'library add check', identifier: 'library_add_check' },
  { name: 'subtitles', identifier: 'subtitles' },
  { name: 'album', identifier: 'album' },
  { name: 'pause circle outline', identifier: 'pause_circle_outline' },
  { name: 'fiber new', identifier: 'fiber_new' },
  { name: 'note', identifier: 'note' },
  { name: 'av timer', identifier: 'av_timer' },
  { name: 'radio', identifier: 'radio' },
  { name: 'games', identifier: 'games' },
  { name: 'playlist play', identifier: 'playlist_play' },
  { name: 'branding watermark', identifier: 'branding_watermark' },
  { name: 'replay circle filled', identifier: 'replay_circle_filled' },
  { name: 'queue', identifier: 'queue' },
  { name: 'forward 10', identifier: 'forward_10' },
  { name: 'replay 10', identifier: 'replay_10' },
  { name: 'closed caption', identifier: 'closed_caption' },
  { name: 'video settings', identifier: 'video_settings' },
  { name: 'featured play list', identifier: 'featured_play_list' },
  { name: 'control camera', identifier: 'control_camera' },
  {
    name: 'playlist add check circle',
    identifier: 'playlist_add_check_circle',
  },
  { name: 'add to queue', identifier: 'add_to_queue' },
  { name: 'slow motion video', identifier: 'slow_motion_video' },
  { name: 'airplay', identifier: 'airplay' },
  { name: 'repeat one', identifier: 'repeat_one' },
  { name: 'call to action', identifier: 'call_to_action' },
  { name: 'snooze', identifier: 'snooze' },
  { name: 'hd', identifier: 'hd' },
  { name: 'high quality', identifier: 'high_quality' },
  { name: 'repeat on', identifier: 'repeat_on' },
  { name: 'closed caption off', identifier: 'closed_caption_off' },
  { name: 'replay 30', identifier: 'replay_30' },
  { name: 'featured video', identifier: 'featured_video' },
  { name: 'playlist remove', identifier: 'playlist_remove' },
  { name: '5g', identifier: '5g' },
  { name: 'shuffle on', identifier: 'shuffle_on' },
  { name: 'forward 30', identifier: 'forward_30' },
  { name: 'music video', identifier: 'music_video' },
  { name: 'replay 5', identifier: 'replay_5' },
  { name: 'queue play next', identifier: 'queue_play_next' },
  { name: 'art track', identifier: 'art_track' },
  { name: 'playlist add circle', identifier: 'playlist_add_circle' },
  { name: 'hearing disabled', identifier: 'hearing_disabled' },
  { name: 'forward 5', identifier: 'forward_5' },
  { name: 'explicit', identifier: 'explicit' },
  { name: '4k', identifier: '4k' },
  { name: 'fiber smart record', identifier: 'fiber_smart_record' },
  { name: 'video label', identifier: 'video_label' },
  { name: 'audio file', identifier: 'audio_file' },
  { name: 'interpreter mode', identifier: 'interpreter_mode' },
  { name: 'video file', identifier: 'video_file' },
  { name: 'repeat one on', identifier: 'repeat_one_on' },
  { name: 'closed caption disabled', identifier: 'closed_caption_disabled' },
  { name: 'surround sound', identifier: 'surround_sound' },
  { name: 'remove from queue', identifier: 'remove_from_queue' },
  { name: 'play disabled', identifier: 'play_disabled' },
  { name: 'web asset off', identifier: 'web_asset_off' },
  { name: 'sd', identifier: 'sd' },
  { name: 'missed video call', identifier: 'missed_video_call' },
  { name: '10k', identifier: '10k' },
  { name: 'fiber pin', identifier: 'fiber_pin' },
  { name: 'fiber dvr', identifier: 'fiber_dvr' },
  { name: '4k plus', identifier: '4k_plus' },
  { name: '1k', identifier: '1k' },
  { name: '2k', identifier: '2k' },
  { name: '1k plus', identifier: '1k_plus' },
  { name: '8k', identifier: '8k' },
  { name: 'lyrics', identifier: 'lyrics' },
  { name: '9k plus', identifier: '9k_plus' },
  { name: '8k plus', identifier: '8k_plus' },
  { name: '5k', identifier: '5k' },
  { name: '3k', identifier: '3k' },
  { name: '5k plus', identifier: '5k_plus' },
  { name: '7k', identifier: '7k' },
  { name: '2k plus', identifier: '2k_plus' },
  { name: '3k plus', identifier: '3k_plus' },
  { name: '9k', identifier: '9k' },
  { name: '6k', identifier: '6k' },
  { name: '6k plus', identifier: '6k_plus' },
  { name: '7k plus', identifier: '7k_plus' },
  { name: 'email', identifier: 'email' },
  { name: 'location on', identifier: 'location_on' },
  { name: 'call', identifier: 'call' },
  { name: 'phone', identifier: 'phone' },
  { name: 'business', identifier: 'business' },
  { name: 'chat', identifier: 'chat' },
  { name: 'mail outline', identifier: 'mail_outline' },
  { name: 'list alt', identifier: 'list_alt' },
  { name: 'vpn key', identifier: 'vpn_key' },
  { name: 'qr code scanner', identifier: 'qr_code_scanner' },
  { name: 'chat bubble outline', identifier: 'chat_bubble_outline' },
  { name: 'alternate email', identifier: 'alternate_email' },
  { name: 'forum', identifier: 'forum' },
  { name: 'chat bubble', identifier: 'chat_bubble' },
  { name: 'textsms', identifier: 'textsms' },
  { name: 'contact mail', identifier: 'contact_mail' },
  { name: 'person search', identifier: 'person_search' },
  { name: 'qr code 2', identifier: 'qr_code_2' },
  { name: 'qr code', identifier: 'qr_code' },
  { name: 'sentiment satisfied alt', identifier: 'sentiment_satisfied_alt' },
  { name: 'message', identifier: 'message' },
  { name: 'comment', identifier: 'comment' },
  { name: 'contacts', identifier: 'contacts' },
  { name: 'app registration', identifier: 'app_registration' },
  { name: 'import contacts', identifier: 'import_contacts' },
  { name: 'contact phone', identifier: 'contact_phone' },
  { name: 'live help', identifier: 'live_help' },
  { name: 'import export', identifier: 'import_export' },
  { name: 'forward to inbox', identifier: 'forward_to_inbox' },
  { name: 'key', identifier: 'key' },
  { name: 'rss feed', identifier: 'rss_feed' },
  { name: 'hourglass bottom', identifier: 'hourglass_bottom' },
  { name: 'hourglass top', identifier: 'hourglass_top' },
  { name: 'mark email read', identifier: 'mark_email_read' },
  { name: 'read more', identifier: 'read_more' },
  { name: 'mark email unread', identifier: 'mark_email_unread' },
  { name: 'call end', identifier: 'call_end' },
  { name: 'more time', identifier: 'more_time' },
  { name: 'document scanner', identifier: 'document_scanner' },
  { name: 'clear all', identifier: 'clear_all' },
  { name: 'hub', identifier: 'hub' },
  { name: 'dialpad', identifier: 'dialpad' },
  { name: 'phone enabled', identifier: 'phone_enabled' },
  { name: 'mark chat unread', identifier: 'mark_chat_unread' },
  { name: '3p', identifier: '3p' },
  { name: 'cancel presentation', identifier: 'cancel_presentation' },
  { name: 'screen share', identifier: 'screen_share' },
  { name: 'call made', identifier: 'call_made' },
  { name: 'call split', identifier: 'call_split' },
  { name: 'unsubscribe', identifier: 'unsubscribe' },
  { name: 'present to all', identifier: 'present_to_all' },
  { name: 'add ic call', identifier: 'add_ic_call' },
  { name: 'domain verification', identifier: 'domain_verification' },
  { name: 'mark chat read', identifier: 'mark_chat_read' },
  { name: 'phonelink ring', identifier: 'phonelink_ring' },
  { name: 'stay current portrait', identifier: 'stay_current_portrait' },
  { name: 'call received', identifier: 'call_received' },
  { name: 'phonelink lock', identifier: 'phonelink_lock' },
  { name: 'phone disabled', identifier: 'phone_disabled' },
  { name: 'duo', identifier: 'duo' },
  { name: 'ring volume', identifier: 'ring_volume' },
  { name: 'phonelink setup', identifier: 'phonelink_setup' },
  { name: 'location off', identifier: 'location_off' },
  { name: 'stay primary portrait', identifier: 'stay_primary_portrait' },
  { name: 'swap calls', identifier: 'swap_calls' },
  { name: 'co present', identifier: 'co_present' },
  { name: 'voicemail', identifier: 'voicemail' },
  { name: 'call merge', identifier: 'call_merge' },
  { name: 'mobile screen share', identifier: 'mobile_screen_share' },
  { name: 'phonelink erase', identifier: 'phonelink_erase' },
  { name: 'person add disabled', identifier: 'person_add_disabled' },
  { name: 'cell tower', identifier: 'cell_tower' },
  { name: 'domain disabled', identifier: 'domain_disabled' },
  { name: 'call missed outgoing', identifier: 'call_missed_outgoing' },
  { name: 'cell wifi', identifier: 'cell_wifi' },
  { name: 'speaker phone', identifier: 'speaker_phone' },
  { name: 'desktop access disabled', identifier: 'desktop_access_disabled' },
  { name: 'stop screen share', identifier: 'stop_screen_share' },
  { name: 'call missed', identifier: 'call_missed' },
  { name: 'spoke', identifier: 'spoke' },
  { name: 'print disabled', identifier: 'print_disabled' },
  { name: 'pause presentation', identifier: 'pause_presentation' },
  { name: 'dialer sip', identifier: 'dialer_sip' },
  { name: 'invert colors off', identifier: 'invert_colors_off' },
  { name: 'rtt', identifier: 'rtt' },
  { name: 'wifi calling', identifier: 'wifi_calling' },
  { name: 'portable wifi off', identifier: 'portable_wifi_off' },
  { name: 'comments disabled', identifier: 'comments_disabled' },
  { name: 'stay current landscape', identifier: 'stay_current_landscape' },
  { name: 'sip', identifier: 'sip' },
  { name: 'nat', identifier: 'nat' },
  { name: 'stay primary landscape', identifier: 'stay_primary_landscape' },
  { name: 'no sim', identifier: 'no_sim' },
  { name: 'mark unread chat alt', identifier: 'mark_unread_chat_alt' },
  { name: 'send time extension', identifier: 'send_time_extension' },
  { name: 'key off', identifier: 'key_off' },
  { name: 'vpn key off', identifier: 'vpn_key_off' },
  { name: 'mail lock', identifier: 'mail_lock' },
  { name: 'contact emergency', identifier: 'contact_emergency' },
  { name: 'add', identifier: 'add' },
  { name: 'add circle outline', identifier: 'add_circle_outline' },
  { name: 'content copy', identifier: 'content_copy' },
  { name: 'add circle', identifier: 'add_circle' },
  { name: 'send', identifier: 'send' },
  { name: 'clear', identifier: 'clear' },
  { name: 'mail', identifier: 'mail' },
  { name: 'save', identifier: 'save' },
  { name: 'link', identifier: 'link' },
  { name: 'remove', identifier: 'remove' },
  { name: 'filter list', identifier: 'filter_list' },
  { name: 'inventory 2', identifier: 'inventory_2' },
  { name: 'insights', identifier: 'insights' },
  { name: 'inventory', identifier: 'inventory' },
  { name: 'sort', identifier: 'sort' },
  { name: 'remove circle outline', identifier: 'remove_circle_outline' },
  { name: 'bolt', identifier: 'bolt' },
  { name: 'flag', identifier: 'flag' },
  { name: 'reply', identifier: 'reply' },
  { name: 'add box', identifier: 'add_box' },
  { name: 'remove circle', identifier: 'remove_circle' },
  { name: 'create', identifier: 'create' },
  { name: 'push pin', identifier: 'push_pin' },
  { name: 'block', identifier: 'block' },
  { name: 'calculate', identifier: 'calculate' },
  { name: 'undo', identifier: 'undo' },
  { name: 'how to reg', identifier: 'how_to_reg' },
  { name: 'content paste', identifier: 'content_paste' },
  { name: 'report', identifier: 'report' },
  { name: 'file copy', identifier: 'file_copy' },
  { name: 'shield', identifier: 'shield' },
  { name: 'backspace', identifier: 'backspace' },
  { name: 'archive', identifier: 'archive' },
  { name: 'save alt', identifier: 'save_alt' },
  { name: 'policy', identifier: 'policy' },
  { name: 'tag', identifier: 'tag' },
  { name: 'change circle', identifier: 'change_circle' },
  { name: 'redo', identifier: 'redo' },
  { name: 'content cut', identifier: 'content_cut' },
  { name: 'forward', identifier: 'forward' },
  { name: 'inbox', identifier: 'inbox' },
  { name: 'outlined flag', identifier: 'outlined_flag' },
  { name: 'drafts', identifier: 'drafts' },
  { name: 'link off', identifier: 'link_off' },
  { name: 'biotech', identifier: 'biotech' },
  { name: 'ballot', identifier: 'ballot' },
  { name: 'report gmailerrorred', identifier: 'report_gmailerrorred' },
  { name: 'markunread', identifier: 'markunread' },
  { name: 'stacked bar chart', identifier: 'stacked_bar_chart' },
  { name: 'delete sweep', identifier: 'delete_sweep' },
  { name: 'square foot', identifier: 'square_foot' },
  { name: 'stream', identifier: 'stream' },
  { name: 'add link', identifier: 'add_link' },
  { name: 'where to vote', identifier: 'where_to_vote' },
  { name: 'copy all', identifier: 'copy_all' },
  { name: 'move to inbox', identifier: 'move_to_inbox' },
  { name: 'dynamic feed', identifier: 'dynamic_feed' },
  { name: 'waves', identifier: 'waves' },
  { name: 'unarchive', identifier: 'unarchive' },
  { name: 'reply all', identifier: 'reply_all' },
  { name: 'select all', identifier: 'select_all' },
  { name: 'low priority', identifier: 'low_priority' },
  { name: 'text format', identifier: 'text_format' },
  { name: 'content paste search', identifier: 'content_paste_search' },
  { name: 'weekend', identifier: 'weekend' },
  { name: 'font download', identifier: 'font_download' },
  { name: 'how to vote', identifier: 'how_to_vote' },
  { name: 'upcoming', identifier: 'upcoming' },
  { name: 'gesture', identifier: 'gesture' },
  { name: 'attribution', identifier: 'attribution' },
  { name: 'save as', identifier: 'save_as' },
  { name: 'next week', identifier: 'next_week' },
  { name: 'content paste go', identifier: 'content_paste_go' },
  { name: 'flag circle', identifier: 'flag_circle' },
  { name: 'content paste off', identifier: 'content_paste_off' },
  { name: 'filter list off', identifier: 'filter_list_off' },
  { name: 'report off', identifier: 'report_off' },
  { name: 'font download off', identifier: 'font_download_off' },
  { name: 'deselect', identifier: 'deselect' },
  { name: 'web stories', identifier: 'web_stories' },
  { name: 'light mode', identifier: 'light_mode' },
  { name: 'restart alt', identifier: 'restart_alt' },
  { name: 'dark mode', identifier: 'dark_mode' },
  { name: 'task', identifier: 'task' },
  { name: 'summarize', identifier: 'summarize' },
  { name: 'password', identifier: 'password' },
  { name: 'sell', identifier: 'sell' },
  { name: 'signal cellular alt', identifier: 'signal_cellular_alt' },
  { name: 'devices', identifier: 'devices' },
  { name: 'settings suggest', identifier: 'settings_suggest' },
  { name: 'quiz', identifier: 'quiz' },
  { name: 'widgets', identifier: 'widgets' },
  { name: 'storage', identifier: 'storage' },
  { name: 'thermostat', identifier: 'thermostat' },
  { name: 'battery full', identifier: 'battery_full' },
  { name: 'credit score', identifier: 'credit_score' },
  { name: 'gps fixed', identifier: 'gps_fixed' },
  { name: 'medication', identifier: 'medication' },
  { name: 'price check', identifier: 'price_check' },
  { name: 'pin', identifier: 'pin' },
  { name: 'gpp good', identifier: 'gpp_good' },
  { name: 'price change', identifier: 'price_change' },
  { name: 'tungsten', identifier: 'tungsten' },
  { name: 'battery charging full', identifier: 'battery_charging_full' },
  { name: 'fmd good', identifier: 'fmd_good' },
  { name: 'reviews', identifier: 'reviews' },
  { name: 'note alt', identifier: 'note_alt' },
  { name: 'air', identifier: 'air' },
  { name: 'graphic eq', identifier: 'graphic_eq' },
  { name: 'bluetooth', identifier: 'bluetooth' },
  { name: 'dvr', identifier: 'dvr' },
  { name: 'nightlight', identifier: 'nightlight' },
  { name: 'sports score', identifier: 'sports_score' },
  { name: 'access time', identifier: 'access_time' },
  { name: 'water', identifier: 'water' },
  { name: 'share location', identifier: 'share_location' },
  { name: 'monitor heart', identifier: 'monitor_heart' },
  { name: 'gpp maybe', identifier: 'gpp_maybe' },
  { name: 'cable', identifier: 'cable' },
  { name: 'location searching', identifier: 'location_searching' },
  { name: 'cameraswitch', identifier: 'cameraswitch' },
  { name: 'shortcut', identifier: 'shortcut' },
  { name: 'device thermostat', identifier: 'device_thermostat' },
  { name: 'airplane ticket', identifier: 'airplane_ticket' },
  { name: 'wallpaper', identifier: 'wallpaper' },
  { name: 'monitor weight', identifier: 'monitor_weight' },
  { name: 'radar', identifier: 'radar' },
  { name: 'data usage', identifier: 'data_usage' },
  { name: 'signal wifi 4 bar', identifier: 'signal_wifi_4_bar' },
  { name: 'gpp bad', identifier: 'gpp_bad' },
  { name: 'developer mode', identifier: 'developer_mode' },
  { name: 'battery std', identifier: 'battery_std' },
  { name: 'mode night', identifier: 'mode_night' },
  { name: 'bloodtype', identifier: 'bloodtype' },
  { name: 'wifi tethering', identifier: 'wifi_tethering' },
  { name: 'signal cellular 4 bar', identifier: 'signal_cellular_4_bar' },
  { name: 'flashlight on', identifier: 'flashlight_on' },
  { name: 'network wifi', identifier: 'network_wifi' },
  { name: 'fmd bad', identifier: 'fmd_bad' },
  { name: 'splitscreen', identifier: 'splitscreen' },
  { name: 'access time filled', identifier: 'access_time_filled' },
  { name: 'airplanemode active', identifier: 'airplanemode_active' },
  { name: 'mobile friendly', identifier: 'mobile_friendly' },
  { name: 'sim card download', identifier: 'sim_card_download' },
  { name: 'battery alert', identifier: 'battery_alert' },
  { name: 'send to mobile', identifier: 'send_to_mobile' },
  { name: 'screen search desktop', identifier: 'screen_search_desktop' },
  { name: 'usb', identifier: 'usb' },
  { name: 'lens blur', identifier: 'lens_blur' },
  {
    name: 'signal wifi statusbar 4 bar',
    identifier: 'signal_wifi_statusbar_4_bar',
  },
  { name: 'discount', identifier: 'discount' },
  { name: 'screen rotation', identifier: 'screen_rotation' },
  {
    name: 'signal wifi statusbar connected no internet 4',
    identifier: 'signal_wifi_statusbar_connected_no_internet_4',
  },
  {
    name: 'system security update good',
    identifier: 'system_security_update_good',
  },
  { name: 'gps not fixed', identifier: 'gps_not_fixed' },
  { name: 'bluetooth connected', identifier: 'bluetooth_connected' },
  { name: 'remember me', identifier: 'remember_me' },
  { name: 'pattern', identifier: 'pattern' },
  { name: 'nfc', identifier: 'nfc' },
  { name: 'brightness high', identifier: 'brightness_high' },
  { name: 'mode standby', identifier: 'mode_standby' },
  { name: 'battery saver', identifier: 'battery_saver' },
  { name: 'play lesson', identifier: 'play_lesson' },
  { name: 'lan', identifier: 'lan' },
  { name: 'storm', identifier: 'storm' },
  { name: 'network cell', identifier: 'network_cell' },
  { name: 'data saver off', identifier: 'data_saver_off' },
  { name: 'screenshot', identifier: 'screenshot' },
  { name: 'brightness medium', identifier: 'brightness_medium' },
  { name: 'signal wifi 0 bar', identifier: 'signal_wifi_0_bar' },
  { name: 'brightness low', identifier: 'brightness_low' },
  { name: 'data saver on', identifier: 'data_saver_on' },
  { name: 'grid 4x4', identifier: 'grid_4x4' },
  { name: 'bluetooth searching', identifier: 'bluetooth_searching' },
  { name: 'mobiledata off', identifier: 'mobiledata_off' },
  { name: 'ad units', identifier: 'ad_units' },
  { name: 'bluetooth disabled', identifier: 'bluetooth_disabled' },
  { name: 'security update good', identifier: 'security_update_good' },
  { name: 'hdr auto', identifier: 'hdr_auto' },
  { name: 'battery unknown', identifier: 'battery_unknown' },
  { name: 'signal wifi off', identifier: 'signal_wifi_off' },
  { name: 'signal wifi bad', identifier: 'signal_wifi_bad' },
  {
    name: 'settings system daydream',
    identifier: 'settings_system_daydream',
  },
  { name: 'wifi calling 3', identifier: 'wifi_calling_3' },
  { name: 'access alarms', identifier: 'access_alarms' },
  { name: 'battery 5 bar', identifier: 'battery_5_bar' },
  {
    name: 'signal wifi connected no internet 4',
    identifier: 'signal_wifi_connected_no_internet_4',
  },
  { name: 'aod', identifier: 'aod' },
  { name: 'add to home screen', identifier: 'add_to_home_screen' },
  { name: 'security update', identifier: 'security_update' },
  { name: 'ssid chart', identifier: 'ssid_chart' },
  { name: 'signal cellular 0 bar', identifier: 'signal_cellular_0_bar' },
  { name: 'flashlight off', identifier: 'flashlight_off' },
  { name: 'flourescent', identifier: 'flourescent' },
  { name: 'access alarm', identifier: 'access_alarm' },
  { name: 'gps off', identifier: 'gps_off' },
  { name: '4g mobiledata', identifier: '4g_mobiledata' },
  { name: 'grid 3x3', identifier: 'grid_3x3' },
  {
    name: 'signal wifi statusbar null',
    identifier: 'signal_wifi_statusbar_null',
  },
  { name: 'battery 4 bar', identifier: 'battery_4_bar' },
  { name: 'sd storage', identifier: 'sd_storage' },
  { name: 'reset tv', identifier: 'reset_tv' },
  { name: 'wifi lock', identifier: 'wifi_lock' },
  { name: 'battery 0 bar', identifier: 'battery_0_bar' },
  { name: 'battery 6 bar', identifier: 'battery_6_bar' },
  { name: 'brightness auto', identifier: 'brightness_auto' },
  {
    name: 'do not disturb on total silence',
    identifier: 'do_not_disturb_on_total_silence',
  },
  {
    name: 'signal cellular connected no internet 4 bar',
    identifier: 'signal_cellular_connected_no_internet_4_bar',
  },
  { name: 'airplanemode inactive', identifier: 'airplanemode_inactive' },
  { name: '1x mobiledata', identifier: '1x_mobiledata' },
  { name: 'nearby error', identifier: 'nearby_error' },
  { name: 'security update warning', identifier: 'security_update_warning' },
  {
    name: 'signal cellular connected no internet 0 bar',
    identifier: 'signal_cellular_connected_no_internet_0_bar',
  },
  { name: 'screen lock portrait', identifier: 'screen_lock_portrait' },
  { name: 'system security update', identifier: 'system_security_update' },
  { name: 'battery 3 bar', identifier: 'battery_3_bar' },
  {
    name: 'system security update warning',
    identifier: 'system_security_update_warning',
  },
  { name: 'wifi tethering off', identifier: 'wifi_tethering_off' },
  { name: 'edgesensor high', identifier: 'edgesensor_high' },
  { name: 'punch clock', identifier: 'punch_clock' },
  { name: '4g plus mobiledata', identifier: '4g_plus_mobiledata' },
  { name: 'battery 1 bar', identifier: 'battery_1_bar' },
  { name: 'signal wifi 4 bar lock', identifier: 'signal_wifi_4_bar_lock' },
  { name: 'lte mobiledata', identifier: 'lte_mobiledata' },
  { name: 'add alarm', identifier: 'add_alarm' },
  { name: 'signal cellular off', identifier: 'signal_cellular_off' },
  { name: 'media bluetooth on', identifier: 'media_bluetooth_on' },
  { name: 'bluetooth drive', identifier: 'bluetooth_drive' },
  { name: 'signal cellular nodata', identifier: 'signal_cellular_nodata' },
  { name: 'wifi password', identifier: 'wifi_password' },
  { name: 'location disabled', identifier: 'location_disabled' },
  { name: 'signal cellular null', identifier: 'signal_cellular_null' },
  { name: 'mobile off', identifier: 'mobile_off' },
  { name: 'medication liquid', identifier: 'medication_liquid' },
  { name: '30fps', identifier: '30fps' },
  { name: 'battery 2 bar', identifier: 'battery_2_bar' },
  { name: 'grid goldenratio', identifier: 'grid_goldenratio' },
  { name: 'screen lock rotation', identifier: 'screen_lock_rotation' },
  { name: 'rsvp', identifier: 'rsvp' },
  { name: 'edgesensor low', identifier: 'edgesensor_low' },
  { name: '3g mobiledata', identifier: '3g_mobiledata' },
  { name: '60fps', identifier: '60fps' },
  { name: 'screen lock landscape', identifier: 'screen_lock_landscape' },
  { name: 'lte plus mobiledata', identifier: 'lte_plus_mobiledata' },
  { name: 'usb off', identifier: 'usb_off' },
  { name: 'phishing', identifier: 'phishing' },
  { name: 'timer 10 select', identifier: 'timer_10_select' },
  { name: 'signal cellular no sim', identifier: 'signal_cellular_no_sim' },
  { name: 'screenshot monitor', identifier: 'screenshot_monitor' },
  { name: 'g mobiledata', identifier: 'g_mobiledata' },
  { name: 'timer 3 select', identifier: 'timer_3_select' },
  { name: 'wifi find', identifier: 'wifi_find' },
  { name: 'h mobiledata', identifier: 'h_mobiledata' },
  { name: 'network wifi 3 bar', identifier: 'network_wifi_3_bar' },
  { name: 'network wifi 1 bar', identifier: 'network_wifi_1_bar' },
  { name: 'media bluetooth off', identifier: 'media_bluetooth_off' },
  { name: 'e mobiledata', identifier: 'e_mobiledata' },
  { name: 'r mobiledata', identifier: 'r_mobiledata' },
  { name: 'h plus mobiledata', identifier: 'h_plus_mobiledata' },
  { name: 'wifi tethering error', identifier: 'wifi_tethering_error' },
  { name: 'hdr on select', identifier: 'hdr_on_select' },
  { name: 'hdr auto select', identifier: 'hdr_auto_select' },
  { name: 'wifi channel', identifier: 'wifi_channel' },
  { name: 'network wifi 2 bar', identifier: 'network_wifi_2_bar' },
  { name: 'nearby off', identifier: 'nearby_off' },
  { name: 'wifi 2 bar', identifier: 'wifi_2_bar' },
  { name: 'hdr off select', identifier: 'hdr_off_select' },
  {
    name: 'signal cellular alt 2 bar',
    identifier: 'signal_cellular_alt_2_bar',
  },
  {
    name: 'signal cellular alt 1 bar',
    identifier: 'signal_cellular_alt_1_bar',
  },
  { name: 'wifi 1 bar', identifier: 'wifi_1_bar' },
  { name: 'devices fold', identifier: 'devices_fold' },
  { name: 'dataset', identifier: 'dataset' },
  { name: 'dataset linked', identifier: 'dataset_linked' },
  { name: 'macro off', identifier: 'macro_off' },
  { name: 'attach money', identifier: 'attach_money' },
  { name: 'format list bulleted', identifier: 'format_list_bulleted' },
  { name: 'mode edit', identifier: 'mode_edit' },
  { name: 'edit note', identifier: 'edit_note' },
  { name: 'monetization on', identifier: 'monetization_on' },
  { name: 'attach file', identifier: 'attach_file' },
  { name: 'post add', identifier: 'post_add' },
  { name: 'bar chart', identifier: 'bar_chart' },
  { name: 'checklist', identifier: 'checklist' },
  { name: 'drag handle', identifier: 'drag_handle' },
  { name: 'insert drive file', identifier: 'insert_drive_file' },
  { name: 'show chart', identifier: 'show_chart' },
  { name: 'format quote', identifier: 'format_quote' },
  { name: 'format list numbered', identifier: 'format_list_numbered' },
  { name: 'border color', identifier: 'border_color' },
  { name: 'table chart', identifier: 'table_chart' },
  { name: 'pie chart', identifier: 'pie_chart' },
  { name: 'notes', identifier: 'notes' },
  { name: 'query stats', identifier: 'query_stats' },
  { name: 'format bold', identifier: 'format_bold' },
  { name: 'insert photo', identifier: 'insert_photo' },
  { name: 'text fields', identifier: 'text_fields' },
  { name: 'insert emoticon', identifier: 'insert_emoticon' },
  { name: 'title', identifier: 'title' },
  { name: 'table rows', identifier: 'table_rows' },
  { name: 'auto graph', identifier: 'auto_graph' },
  { name: 'publish', identifier: 'publish' },
  { name: 'mode', identifier: 'mode' },
  { name: 'insert chart outlined', identifier: 'insert_chart_outlined' },
  { name: 'checklist rtl', identifier: 'checklist_rtl' },
  { name: 'mode comment', identifier: 'mode_comment' },
  { name: 'insert invitation', identifier: 'insert_invitation' },
  { name: 'draw', identifier: 'draw' },
  { name: 'insert link', identifier: 'insert_link' },
  { name: 'functions', identifier: 'functions' },
  { name: 'mode edit outline', identifier: 'mode_edit_outline' },
  { name: 'format italic', identifier: 'format_italic' },
  { name: 'format align left', identifier: 'format_align_left' },
  { name: 'horizontal rule', identifier: 'horizontal_rule' },
  { name: 'format color fill', identifier: 'format_color_fill' },
  { name: 'add comment', identifier: 'add_comment' },
  { name: 'insert chart', identifier: 'insert_chart' },
  { name: 'linear scale', identifier: 'linear_scale' },
  { name: 'format size', identifier: 'format_size' },
  { name: 'stacked line chart', identifier: 'stacked_line_chart' },
  { name: 'format underlined', identifier: 'format_underlined' },
  { name: 'bubble chart', identifier: 'bubble_chart' },
  { name: 'insert comment', identifier: 'insert_comment' },
  { name: 'money off', identifier: 'money_off' },
  { name: 'vertical align bottom', identifier: 'vertical_align_bottom' },
  { name: 'height', identifier: 'height' },
  { name: 'vertical align top', identifier: 'vertical_align_top' },
  { name: 'format align center', identifier: 'format_align_center' },
  { name: 'format paint', identifier: 'format_paint' },
  { name: 'schema', identifier: 'schema' },
  { name: 'format color text', identifier: 'format_color_text' },
  { name: 'area chart', identifier: 'area_chart' },
  { name: 'format align right', identifier: 'format_align_right' },
  { name: 'scatter plot', identifier: 'scatter_plot' },
  {
    name: 'format list numbered rtl',
    identifier: 'format_list_numbered_rtl',
  },
  { name: 'highlight', identifier: 'highlight' },
  { name: 'merge type', identifier: 'merge_type' },
  { name: 'format align justify', identifier: 'format_align_justify' },
  { name: 'square', identifier: 'square' },
  { name: 'add chart', identifier: 'add_chart' },
  { name: 'format shapes', identifier: 'format_shapes' },
  { name: 'money off csred', identifier: 'money_off_csred' },
  { name: 'pie chart outline', identifier: 'pie_chart_outline' },
  { name: 'numbers', identifier: 'numbers' },
  { name: 'short text', identifier: 'short_text' },
  { name: 'format indent increase', identifier: 'format_indent_increase' },
  { name: 'align horizontal left', identifier: 'align_horizontal_left' },
  { name: 'strikethrough s', identifier: 'strikethrough_s' },
  { name: 'vertical align center', identifier: 'vertical_align_center' },
  { name: 'format color reset', identifier: 'format_color_reset' },
  { name: 'data object', identifier: 'data_object' },
  { name: 'multiline chart', identifier: 'multiline_chart' },
  { name: 'score', identifier: 'score' },
  { name: 'border all', identifier: 'border_all' },
  { name: 'hexagon', identifier: 'hexagon' },
  { name: 'space bar', identifier: 'space_bar' },
  { name: 'format indent decrease', identifier: 'format_indent_decrease' },
  { name: 'format clear', identifier: 'format_clear' },
  { name: 'rectangle', identifier: 'rectangle' },
  { name: 'format line spacing', identifier: 'format_line_spacing' },
  { name: 'move up', identifier: 'move_up' },
  { name: 'align vertical bottom', identifier: 'align_vertical_bottom' },
  { name: 'horizontal distribute', identifier: 'horizontal_distribute' },
  { name: 'align horizontal center', identifier: 'align_horizontal_center' },
  { name: 'format strikethrough', identifier: 'format_strikethrough' },
  { name: 'move down', identifier: 'move_down' },
  { name: 'align horizontal right', identifier: 'align_horizontal_right' },
  { name: 'vertical distribute', identifier: 'vertical_distribute' },
  { name: 'superscript', identifier: 'superscript' },
  { name: 'candlestick chart', identifier: 'candlestick_chart' },
  { name: 'margin', identifier: 'margin' },
  { name: 'text increase', identifier: 'text_increase' },
  { name: 'wrap text', identifier: 'wrap_text' },
  { name: 'border clear', identifier: 'border_clear' },
  { name: 'align vertical top', identifier: 'align_vertical_top' },
  { name: 'subscript', identifier: 'subscript' },
  { name: 'align vertical center', identifier: 'align_vertical_center' },
  { name: 'polyline', identifier: 'polyline' },
  { name: 'border style', identifier: 'border_style' },
  { name: 'data array', identifier: 'data_array' },
  { name: 'padding', identifier: 'padding' },
  { name: 'border outer', identifier: 'border_outer' },
  { name: 'pentagon', identifier: 'pentagon' },
  { name: 'text decrease', identifier: 'text_decrease' },
  { name: 'line axis', identifier: 'line_axis' },
  { name: 'insert page break', identifier: 'insert_page_break' },
  { name: 'border inner', identifier: 'border_inner' },
  { name: 'border left', identifier: 'border_left' },
  { name: 'border bottom', identifier: 'border_bottom' },
  {
    name: 'format textdirection l to r',
    identifier: 'format_textdirection_l_to_r',
  },
  { name: 'border vertical', identifier: 'border_vertical' },
  { name: 'border horizontal', identifier: 'border_horizontal' },
  {
    name: 'format textdirection r to l',
    identifier: 'format_textdirection_r_to_l',
  },
  { name: 'border top', identifier: 'border_top' },
  { name: 'border right', identifier: 'border_right' },
  { name: 'shape line', identifier: 'shape_line' },
  { name: 'type specimen', identifier: 'type_specimen' },
  { name: 'file download', identifier: 'file_download' },
  { name: 'file download', identifier: 'file_download' },
  { name: 'file upload', identifier: 'file_upload' },
  { name: 'download', identifier: 'download' },
  { name: 'folder', identifier: 'folder' },
  { name: 'grid view', identifier: 'grid_view' },
  { name: 'upload file', identifier: 'upload_file' },
  { name: 'cloud upload', identifier: 'cloud_upload' },
  { name: 'folder open', identifier: 'folder_open' },
  { name: 'cloud', identifier: 'cloud' },
  { name: 'text snippet', identifier: 'text_snippet' },
  { name: 'request quote', identifier: 'request_quote' },
  { name: 'cloud download', identifier: 'cloud_download' },
  {
    name: 'drive file rename outline',
    identifier: 'drive_file_rename_outline',
  },
  { name: 'upload', identifier: 'upload' },
  { name: 'attachment', identifier: 'attachment' },
  { name: 'download for offline', identifier: 'download_for_offline' },
  { name: 'create new folder', identifier: 'create_new_folder' },
  { name: 'downloading', identifier: 'downloading' },
  { name: 'newspaper', identifier: 'newspaper' },
  { name: 'folder shared', identifier: 'folder_shared' },
  { name: 'cloud done', identifier: 'cloud_done' },
  { name: 'topic', identifier: 'topic' },
  { name: 'download done', identifier: 'download_done' },
  { name: 'cloud queue', identifier: 'cloud_queue' },
  { name: 'workspaces', identifier: 'workspaces' },
  { name: 'approval', identifier: 'approval' },
  { name: 'cloud off', identifier: 'cloud_off' },
  { name: 'drive file move', identifier: 'drive_file_move' },
  { name: 'drive folder upload', identifier: 'drive_folder_upload' },
  { name: 'file download done', identifier: 'file_download_done' },
  { name: 'file open', identifier: 'file_open' },
  { name: 'attach email', identifier: 'attach_email' },
  { name: 'rule folder', identifier: 'rule_folder' },
  { name: 'cloud sync', identifier: 'cloud_sync' },
  { name: 'cloud circle', identifier: 'cloud_circle' },
  { name: 'snippet folder', identifier: 'snippet_folder' },
  { name: 'folder zip', identifier: 'folder_zip' },
  { name: 'file download off', identifier: 'file_download_off' },
  { name: 'folder copy', identifier: 'folder_copy' },
  { name: 'difference', identifier: 'difference' },
  { name: 'drive file move rtl', identifier: 'drive_file_move_rtl' },
  { name: 'folder delete', identifier: 'folder_delete' },
  { name: 'folder off', identifier: 'folder_off' },
  { name: 'format overline', identifier: 'format_overline' },
];

export const WELCOME_MESSAGE = "Find your desired Angular Material icons";
export const SHOW_ENTIRE_LIST = "Explore all icons";